# Generated by Django 6.1.1 on 2026-09-18 15:30

from django.db import migrations, models
from django.db.migrations.state import ModelState, ProjectState


def retire_backup_foreign_key(apps, schema_editor):
    """Keep retired backup records without blocking photograph deletion."""
    connection = schema_editor.connection
    table = "backup_filebackup"
    with connection.cursor() as cursor:
        if table not in connection.introspection.table_names(cursor):
            return
        constraints = connection.introspection.get_constraints(cursor, table)
    if not any(
        value["columns"] == ["source_id"]
        and value["foreign_key"] == ("core_file", "id")
        for value in constraints.values()
    ):
        return

    before = ProjectState.from_apps(apps)
    before.add_model(
        ModelState(
            "backup",
            "FileBackup",
            [
                ("id", models.AutoField(primary_key=True)),
                ("done", models.DateTimeField(null=True, blank=True)),
                ("source", models.ForeignKey("core.File", on_delete=models.CASCADE)),
            ],
        )
    )
    operation = migrations.AlterField(
        "filebackup",
        "source",
        models.ForeignKey("core.File", on_delete=models.CASCADE, db_constraint=False),
    )
    after = before.clone()
    operation.state_forwards("backup", after)
    operation.database_forwards("backup", schema_editor, before, after)


class Migration(migrations.Migration):

    dependencies = [
        ('rola_integration', '0001_portable'),
    ]

    operations = [
        migrations.RunPython(retire_backup_foreign_key, migrations.RunPython.noop),
    ]
